"""Batch narration over real NestJS Control Tower alerts.

Control Tower is not an agent or chat entry point. This module fetches the
backend's structured alerts and makes one lightweight narration-model call
per alert. Backend category, severity, message, data, and referenceDate are
never recalculated or regenerated by the model.
"""

from __future__ import annotations

import asyncio
import json
from typing import Optional

from pydantic import BaseModel, Field
from strands.types.content import Message

from clients import BackendHttpClient
from config.settings import settings
from tools.schemas.control_tower_schema import Alert, AlertCategory, NarratedAlert

NARRATION_SYSTEM_PROMPT = """\
You write short, plain-language alert narrations for warehouse and inventory
operations staff. Given one structured backend alert, produce exactly:

1. narrative: 1-3 sentences explaining the backend message and evidence.
2. proposed_action: one concrete next step, phrased as an instruction or
   recommendation, never as an action that has already happened.

Hard rules:
- Never invent facts or recalculate category, severity, quantities, dates,
  risk, thresholds, scores, or any other business result.
- Treat the supplied backend category, severity, message, and data as the
  source of truth and preserve their meaning exactly.
- For DEAD_STOCK, the business signal is absence of OUTGOING customer
  consumption. Use lastOutgoingMovementAt and daysSinceLastOutgoingMovement
  when present. Do not describe lastMovementAt or daysSinceLastMovement as
  the last customer sale/consumption, because incoming, transfer, and
  adjustment movements do not reset the dead-stock signal.
- Use plain business language and only identifiers/names present in data.
"""


class _NarrationFields(BaseModel):
    narrative: str = Field(..., description="Plain-language explanation of the alert.")
    proposed_action: str = Field(..., description="One concrete recommended next step.")


def get_control_tower_alerts(
    dead_stock_inactivity_days: Optional[int] = None,
    consumption_window_days: Optional[int] = None,
    consumption_threshold_percent: Optional[int] = None,
    reference_date: Optional[str] = None,
) -> list[Alert]:
    """Fetch and validate the real structured NestJS Control Tower alerts."""
    rows = BackendHttpClient().get(
        "/control-tower/alerts",
        query={
            "deadStockInactivityDays": dead_stock_inactivity_days,
            "consumptionWindowDays": consumption_window_days,
            "consumptionThresholdPercent": consumption_threshold_percent,
            "referenceDate": reference_date,
        },
    )
    return [Alert.model_validate(row) for row in rows]


def _build_narration_prompt(alert: Alert) -> str:
    dead_stock_instruction = ""
    if alert.category is AlertCategory.DEAD_STOCK:
        dead_stock_instruction = (
            "\nDead-stock interpretation: describe customer consumption using "
            "lastOutgoingMovementAt/daysSinceLastOutgoingMovement. Do not treat "
            "generic lastMovementAt as the last customer consumption event."
        )
    return (
        f"Backend category: {alert.category.value}\n"
        f"Backend severity: {alert.severity.value}\n"
        f"Backend message: {alert.message}\n"
        f"Backend data: {json.dumps(alert.data, default=str)}\n"
        f"Reference date: {alert.referenceDate.isoformat()}"
        f"{dead_stock_instruction}\n\n"
        "Write only the narrative and proposed_action."
    )


def narrate_alert(alert: Alert) -> NarratedAlert:
    """Add narration while passing every backend field through unchanged."""
    model = settings.build_model("narration")
    messages: list[Message] = [
        {"role": "user", "content": [{"text": _build_narration_prompt(alert)}]}
    ]

    async def _call() -> _NarrationFields:
        last_event: dict | None = None
        async for event in model.structured_output(
            _NarrationFields,
            messages,
            system_prompt=NARRATION_SYSTEM_PROMPT,
        ):
            last_event = event
        if not last_event or "output" not in last_event:
            raise RuntimeError("Narration model call produced no structured output")
        return last_event["output"]

    fields = asyncio.run(_call())
    return NarratedAlert(
        **alert.model_dump(),
        narrative=fields.narrative,
        proposed_action=fields.proposed_action,
    )


def narrate_all_alerts(alerts: list[Alert]) -> list[NarratedAlert]:
    """Narrate a structured alert batch in backend order."""
    return [narrate_alert(alert) for alert in alerts]


def fetch_and_narrate_control_tower_alerts(
    dead_stock_inactivity_days: Optional[int] = None,
    consumption_window_days: Optional[int] = None,
    consumption_threshold_percent: Optional[int] = None,
    reference_date: Optional[str] = None,
) -> list[NarratedAlert]:
    """Real backend-to-narration batch entry point."""
    alerts = get_control_tower_alerts(
        dead_stock_inactivity_days=dead_stock_inactivity_days,
        consumption_window_days=consumption_window_days,
        consumption_threshold_percent=consumption_threshold_percent,
        reference_date=reference_date,
    )
    return narrate_all_alerts(alerts)
